### ISSUE TITLE
compile on Linux fails

### ISSUE THREAD

**Issue by tissatussa** [scs-ben/pygone#2]
hi, i just discovered your engine .. but i can not compile it on Xubuntu 22.04 :

```
~/Compiled/pygone/src$ make
pyminifier -o pygone-mini.py pygone.py && bash shrink.sh && python3 combine.py pygone-mini.py > ../bin/pygone && chmod +x ../bin/pygone && gzexe ../bin/pygone && ls -l ../bin/pygone && rm ../bin/pygone~
/bin/sh: 1: pyminifier: not found
make: *** [Makefile:2: pygone] Error 127
```

i followed your README instructions to build .. it's unclear though : should i edit `prepare.sh` and THEN do `make` ?

**Comment by scs-ben** [comment]
Thanks for the question, this engine is built entirely to compile down to a <4kb binary. The build instructions are for me so I can remember how to do it :D.

There is an already compiled version in bin/pygone15 that will run on Linux (if you have pypy3 installed).

The reason your build is failing is due to the missing library "pyminifier"
You will also need to install pypy3.

**Comment by tissatussa** [comment]
i have `pypy3` .. but when installing `pyminifier` by `pip3`, i get this error :

```
$ pip3 install pyminifier
Collecting pyminifier
  Downloading pyminifier-2.1.tar.gz (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Python 3.X support requires the 2to3 tool.
      It normally comes with Python 3.X but (apparenty) not on your distribution.
      Please find out what package you need to get 2to3and install it.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

i will try your `bin/pygone15` asset !

**Comment by scs-ben** [comment]
Seems like an issue with the Xubuntu Python 3 install.

You can also just run the main file (src/pygone.py) from the terminal (/usr/bin/pypy3 pygone.py). The file has commented out support for fens and basic perft testing (which it fails, for reasons I don't feel like tracing down, likely due to en passant issues).

**Comment by tissatussa** [comment]
indeed i did a basic Xubuntu install, bare minimum, so i have to add all modules myself .. that's OK, i'm used to it, but now i'm stuck : by apt (in Synaptic) i can install '2to3' but then the pyminifier can still not be installed .. also a pip3 module called '2to3' exists, but after installing that, i have the same failure with the pyminifier install :

```
~/Compiled/pygone/src$ whereis 2to3
2to3: /usr/bin/2to3 /usr/share/man/man1/2to3.1.gz

~/Compiled/pygone/src$ pip3 install 2to3
Collecting 2to3
  Downloading 2to3-1.0-py3-none-any.whl (1.7 kB)
Installing collected packages: 2to3
Successfully installed 2to3-1.0

~/Compiled/pygone/src$ pip3 install pyminifier
Collecting pyminifier
  Using cached pyminifier-2.1.tar.gz (47 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Python 3.X support requires the 2to3 tool.
      It normally comes with Python 3.X but (apparenty) not on your distribution.
      Please find out what package you need to get 2to3and install it.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by scs-ben** [comment]
Can you do a local install of Python 3? Maybe that will avoid the issues with the main Python install. You'd have to revise the files to use absolute paths

**Comment by tissatussa** [comment]
mmm .. you suspect my Python 3 install is corrupted ?

**Comment by scs-ben** [comment]
It's missing something that is expected to be there

**Comment by tissatussa** [comment]
yes, the message says

> Please find out what package you need to get 2to3 and install it

so i did .. but "it" couldn't be found .. what do you think ?

**Comment by scs-ben** [comment]
Python gets weird about it's dependencies, you could do `which python3` and then do the pip install through that python path (`/usr/bin/python3 -m pip install 2to3` or something)
