### ISSUE TITLE
python adding bug

### ISSUE THREAD

**Issue by tissatussa** [scs-ben/pygone#4]
i just discovered a bug in your code .. here are the concerning lines in `pygone.py` :

![pygone-add-bug](https://github.com/scs-ben/pygone/assets/1109281/23a37e61-524e-41d7-ae13-e36e25d611a9)

in python (3) the operator '++' (to add one) does NOT exist, in C / CPP it DOES. This is a design decision, see eg. https://www.askpython.com/python/examples/python-increment-operation . However, python3 (or pypy3) gives NO error or warning when using this construct, nothing just happens, the variable will stay the same. Note that `played_moves++` WILL give an error.

it seems this little bug does not influence the working of Pygone (v1.5.4) too much, but when you confirm my case, this should be fixed ..

**Comment by scs-ben** [comment]
Yes, this does seem to be an issue. I'm astounded this doesn't generate an error or warning. It seems to only impact how nodes are counted. I was hoping this would be the big one that is keeping pygone from breaking 3k elo :D.

Thanks for letting me know about this! I spend nearly all my time in C-based languages so ++ is second nature to me.

**Comment by tissatussa** [comment]
> Thanks for letting me know about this! I spend nearly all my time in C-based languages so ++ is second nature to me.

yes, i know those habbits, doing JS and PHP and Python regularly .. i was astounded python gives no error here, i was sure '++' isn't allowed .. my linked article gives good info, i learned something today!

is the project still active / developed ? At this moment i study the code of some open source python chess engines, just to see how they're playing, comparing PSQT's, changing some values, etc. just for fun and learning .. i'm a chess player too .. i encounter many (simple) python engines lack good time management, even when using a compiled binary by pyinstaller (which works very well on Linux, although rather big files might be created, eg. when the well-known `python-chess` module is used).

i think any engine should have good time management, it's essential when playing games with a certain (any) time control, eg. a tournament .. forced moves should be played instantly .. the engine should calculate some average time for a move, regarding the time left and the amount of pieces on the board, etc. .. captures are optional in chess and it's best to let your pieces being captured, and decide how to recapture .. such approach tends to keep pieces on the board, and complex positions are time consuming .. i mean the engine must know when the position needs further investigation, but the process must be stopped instantly (!? not until current depth is fully done) when time is up or it's no use to go deeper.

i also encounter many engines do not always play the same game with same game settings .. i think it's because often a few moves have same eval, so `best move` is just picked randomly .. but in such case maybe it's better to decide `top move` by some move-type or position-type, eg. "non-capture" or "opponent piece restriction" (to be defined).

**Comment by scs-ben** [comment]
This project is not active at the moment. I was going to try to re-write the engine to use magic bitboards but I have not joy in that approach.

I agree that the time management could be improved but within a 4kb budget I think it would be hard to implement much sophistication.

With my engine, the best move is determined entirely based on the evaluation and in cases of ties would be based on how the moves are sorted. There is also the transposition table that could vary slightly between iterations of games and that can influence the evaluation.

**Comment by scs-ben** [comment]
I've resolved the ++ issue with https://github.com/scs-ben/pygone/commit/1d665b5dc09b67e1100405fae678639a5e2fbcf8
